[2024-08-12T05:06:22.751+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-12T05:06:22.770+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_coupang.update_coupang manual__2024-08-12T05:06:20.750495+00:00 [queued]>
[2024-08-12T05:06:22.776+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_coupang.update_coupang manual__2024-08-12T05:06:20.750495+00:00 [queued]>
[2024-08-12T05:06:22.776+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-08-12T05:06:22.786+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): update_coupang> on 2024-08-12 05:06:20.750495+00:00
[2024-08-12T05:06:22.794+0000] {standard_task_runner.py:63} INFO - Started process 186181 to run task
[2024-08-12T05:06:22.797+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_coupang', 'update_coupang', 'manual__2024-08-12T05:06:20.750495+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/coupang_batch.py', '--cfg-path', '/tmp/tmp1n71rnyt']
[2024-08-12T05:06:22.800+0000] {standard_task_runner.py:91} INFO - Job 170: Subtask update_coupang
[2024-08-12T05:06:22.843+0000] {task_command.py:426} INFO - Running <TaskInstance: update_coupang.update_coupang manual__2024-08-12T05:06:20.750495+00:00 [running]> on host bcc9fe6b3d78
[2024-08-12T05:06:22.922+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='zzioni' AIRFLOW_CTX_DAG_ID='update_coupang' AIRFLOW_CTX_TASK_ID='update_coupang' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T05:06:20.750495+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-12T05:06:20.750495+00:00'
[2024-08-12T05:06:22.922+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-12T05:06:23.193+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/354 [00:00<?, ?it/s]
[2024-08-12T05:06:23.194+0000] {logging_mixin.py:188} WARNING - 100%|##########| 354/354 [00:00<00:00, 534094.83it/s]
[2024-08-12T05:06:23.209+0000] {python.py:237} INFO - Done. Returned value was: ([], Series([], Name: price_id, dtype: object))
[2024-08-12T05:06:23.209+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-12T05:06:23.218+0000] {xcom.py:677} ERROR - Object of type tuple is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-08-12T05:06:23.219+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/serialization/serde.py", line 150, in serialize
    return encode(classname or serialized_classname, version, serialize(data, depth + 1))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/serialization/serde.py", line 127, in serialize
    return [serialize(d, depth + 1) for d in o]
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/serialization/serde.py", line 127, in <listcomp>
    return [serialize(d, depth + 1) for d in o]
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas.core.series.Series'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/xcom.py", line 675, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/json.py", line 102, in encode
    o = self.default(o)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type tuple is not JSON serializable
[2024-08-12T05:06:23.231+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=update_coupang, task_id=update_coupang, execution_date=20240812T050620, start_date=20240812T050622, end_date=20240812T050623
[2024-08-12T05:06:23.240+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 170 for task update_coupang (Object of type tuple is not JSON serializable; 186181)
[2024-08-12T05:06:23.288+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-12T05:06:23.317+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T05:06:23.321+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
